language: node_js
sudo: required

cache:
    directories:
      - 'node_modules'
    # cache typescript libraries
      - $HOME/.dts/

matrix:
    fast_finish: true
    include:
      - node_js: '14'
        env: DB="oracledb mssql mysql mysql2 postgres sqlite3" KNEX_TEST_TIMEOUT=60000
      - node_js: '12'
        env: TESTSCRIPT=test:everything DB="oracledb mssql mysql mysql2 postgres sqlite3"
            KNEX_TEST_TIMEOUT=60000
      - node_js: '10'
        env: DB="oracledb mssql mysql mysql2 postgres sqlite3" KNEX_TEST_TIMEOUT=60000
install:
  - npm i


script:
  - npm run ${TESTSCRIPT:-test}

after_success:
  - npm run coveralls

notifications:
    email: false

services:
  - docker
